possessive and doc title formatting info
AshleyHenry15/writing pull request #14
Opened 2023-10-26 22:12 UTC by annikakrilov

fixes #3 and #13

2023-10-26 23:07 UTC, annikakrilov commented
@AshleyHenry15 this is flagging a bunch of broken links that I didn't touch/don't think are actually broken? Not sure if that's known with this repo

2023-10-26 23:38 UTC, annikakrilov commented
You can hold off on reviewing/approving. Going to tag #15 and #16 changes into here since I'm poking at things anyway, unless you'd rather I not :)

2023-10-30 13:25 UTC, AshleyHenry15 requested changes

2023-10-30 13:25 UTC, AshleyHenry15 commented on _quarto.yml
> +              href: writing/mmos.qmd
Did you add this file? I am not seeing it in the pr.

2023-10-30 15:18 UTC, annikakrilov commented on _quarto.yml
> +              href: writing/mmos.qmd
I did and it is in the PR -  but it should be reference/mmos.qmd not under writing. Fixing!

2023-10-30 15:18 UTC, annikakrilov commented on _quarto.yml
> +              href: writing/mmos.qmd
```suggestion
              href: references/mmos.qmd
```

2023-10-30 15:57 UTC, annikakrilov commented on getting-started/prod-docs.qmd
>  ## Product Doc Site Map
```suggestion
## Product doc site map
```

2023-10-30 16:02 UTC, AshleyHenry15 requested changes

2023-10-30 16:02 UTC, AshleyHenry15 commented on writing/style-guide.qmd
> -- Use ending punctuation.
This is a different section than the bulleted list requirements so we still need this OR we can move the punctuation information from the bulleted lists section to the "Lists" section and add verbiage stating that these requirements apply to the following sections.

2023-11-20 15:50 UTC, annikakrilov commented on writing/doc-rules.qmd
> +When you describe a general product/framework that Posit has developed, like Shiny or R Markdown, use the Posit capitalization of the product name.  It does get tricky, but here is an example: if you
Leaving it as Posit makes sense here. Since it's talking about Posit as a company, not Connect/RStudio/Workbench etc. My understanding is this section just means using Posit's proprietary spelling of names, which RStudio would fall under.

2023-11-21 03:35 UTC, AshleyHenry15 requested changes
Two minor changes and once you get those in we can get this merged (and I will publish the site to colorado)

2023-11-21 03:35 UTC, AshleyHenry15 commented on getting-started/prod-docs.qmd
> +posit.co | https://github.com/rstudio/rstudio.com
This isn't accurate - the old rstudio site is still at rstudio/rstudio.com

Posit.co doesn't have a GH repo

2023-11-21 03:35 UTC, AshleyHenry15 commented on writing/style-guide.qmd
> +type | "insert or type in" | Use when directing the user to enter information. For example, Type your password. Use when directing the user to enter specific information. In the field, type "12345."
This should actually stay as "12345" because we only want them to type "12345" and not the period. So, we may have to update the statement above about punctuation inside of quotes for piece of code OR when instructing the user what to type: https://github.com/AshleyHenry15/writing/pull/14/files#diff-56e84a36500e380259696a207a139ecca92842f0cab883bbf0525894eaa079c6R272

2023-11-21 20:53 UTC, AshleyHenry15 approved these changes

2023-11-21 21:07 UTC, merged